### PR TITLE
08 joins

### PR DESCRIPTION
**Pull request by ryanpeek**
Ok! Check this out...I realized I didn't add anything on pivoting...I can probably put a chunk in there pretty quickly on pivoting wide/long from some of the groundwater data, or using the CalEnviroScreen data.

### CODE REVIEW

**Comment by richpauloo** [comment]
Oh I see what you mean. Yes, there's a pivot section missing. Perhaps I'll hold off on review until that section is in there. If we can pivot wide to long and mention how that's the more common operation (going from human-friendly data entry to tidy data that tidyverse functions like) and join it to the data to be used in EDA that would be awesome.

Also, is there a difference between objectives 1 and 3? If not perhaps add the objective, "Learn to identify wide and long data formats, and practice pivoting between these forms"

**Comment by ryanpeek** [comment]
On more thought I suggest we keep this to just joins for now. I can make a short pivot lesson separately, that way we don’t try to mix concepts in the same lesson. I updated as such.

**Comment by richpauloo** [comment]
Did you push updates yet Ryan? I'm not seeing any additional commits. No rush, I can review whenever.

**Comment by ryanpeek** [comment]
@richpauloo, sorry about that, I thought I pushed this up. Other than slight change to objectives, everything is updated and same as before.

**Review by richpauloo — APPROVED** [review]
Looks good to me. I added a few suggestions and minor edits. Feel free to change things back, or accept and merge!

**Pull request merged**
