### PR TITLE
Mod4 data structures

### PR DESCRIPTION
**Pull request by richpauloo**
Initial draft of mod4. I'm going to go through this again, but would appreciate eyes on it. I tried to tee up the dplyr module which comes next by building up to tibbles. This lesson, and mod3 before it (import/export) are sparse in images so that's another thing I need to think about. If there are images for import/export and data structures that you think might be good, please let me know and I'll add em!

### CODE REVIEW

**Comment by ryanpeek** [comment]
great, I'll check this out today, and we can think about some good images/visuals to add in the meantime. I definitely think there's something for import/export in Allison's artwork, and/or we can find a something else. Thanks for pushing this forward, will review soon.

**Comment by richpauloo** [comment]
Thanks Ryan. I've been referring to [this readme](https://github.com/allisonhorst/stats-illustrations) but haven't seen anything for either module. I may not be looking in the right place, or with the right eyes. At our Thursday meeting we can review what we've done so far and brainstorm how to spruce things up. BTW, I love that css you added for the dropdown challenges. It's super clean.

**Comment by ryanpeek** [comment]
I"m reviewing this right now...I'm making some revisions, so happy to chat more if you want. While I think your custom function was great, I think it's still a bit too much too early to use that at the start. I also opted to use "read.csv" for the first part of the lesson, until you introduce tibbles, then load readr and explain from there. Also adding a few screen shots and figures to help spice it up.

**Comment by ryanpeek** [comment]
@richpauloo ok take a look at it now...if you are good with this feel free to merge and delete the branch. I'll be checking back later this evening.

**Comment by richpauloo** [comment]
Wow @ryanpeek, these edits are A+ and you definitely excelled in finding places to insert images, footnotes, asides, and aside figures. Seeing where you spruced things up gives me ideas and inspiration to do more of the same in the next lessons. Thanks! Merging now.

**Pull request merged**
