### PR TITLE
Feature/visualization

### LINKED ISSUE #13: module: Visualization w ggplot2

### PR DESCRIPTION
**Pull request by richpauloo**
Closes #13. 

Can use an extra set of eyes. I'll go through this once more later to clean it up and merge, but wanted you to see it in case you had time before our meeting.

### CODE REVIEW

**Comment by ryanpeek** [comment]
I added some revisions/edits to this. It looks good. One thought which we can decide on later...in the bespoke plot section, I'm wondering if it's too much to introduce maps + sf there...sort of thinking that may be something we want to strip out and you could add some more theme or customization options (putting a legend inside the plot, or something like that). It's just a lot to glance over sf and maps really quickly without much time to explain. I'm open to leaving it in but maybe making it in a collapsed "Advanced Challenge/More Info" box or something so that it won't distract from the simpler lesson. Hope this helps...feel free to merge when you are ready.

**Review by ryanpeek — APPROVED** [review]
Looks good! see my comments in PR

**Comment by richpauloo** [comment]
First, thanks for catching my typos and generally cleaning up the lesson. It was a rough pass and I should've combed though that again. It's much appreciated!

Second, I had the same feeling in the bespoke section. I originally had geom_sf in the geom section but it felt like too much to cram that into an already busy section. I moved it to mapmaking where we can do it justice, left an aside in the "geom_" section about geom_sf and linking to the maps module. Then I expanded a few more options in the bespoke plots section. Let me know what you think.

**Review by ryanpeek — APPROVED** [review]
Looks good! Only thing I couldn't view was the `~/Desktop/legend_help.png`, but I'd say go for it! I think it's cleaned up nicely.

**Comment by richpauloo** [comment]
Ah good catch. I was testing that figure. It's committed now. Thanks!

**Pull request merged**
