### PR TITLE
Module/eda

### LINKED ISSUE #11: module 8: Exploratory Data Analysis (Cleaning Data)

### PR DESCRIPTION
**Pull request by richpauloo**
EDA module is live! Closes #11 

I focused on a building a narrative, but after it was all said and done I realized I didn't find a place for pivot or across.

I need to take a step away and come back at this with fresh eyes.

I didn't get too deep into the CES data, but that would be the way to demonstrate pivot_longer and then going back to wide format. The EDA module just feels really full as it is.

I'm wondering if we can demonstrate it quickly in joins and binds on the calenviro object. I'm not trying to assign you more work, and I'm happy to go in a do it myself, I just want to distribute coursework between modules.

What do you think?

### CODE REVIEW

**Comment by ryanpeek** [comment]
Can you push up the rivers dataset you are using for plots? `data/nhd_sac_major.rds`

I'm reviewing now. Looks good, but I have some suggestions (unsurprisingly 😉 )

**Comment by ryanpeek** [comment]
Ok @richpauloo! See my edits...I think this is really cool and will be fun for folks to play with. I think for teaching we may only need to pick/cover 1-2 questions to go through, but this is flexible to cover different content based on where folks are.

I think there are three main pieces that need to be updated/addressed:
 - Need some additional info on why GW depth > 250 is erroneous...either a quick caption/sidebar, or reference.
 - If we want to add rivers to the maps (which would be nice), need to push that data up (or create it, which I'm happy to do if needed) and add it as a geom_sf to the maps/mapviews.
 - The part where we identify the erroneous groundwater observation (outlier) is great, but we need to walk through in more detail how you found that specific ID value. I offered one approach using **`View()`** but if you have an alternate approach that is simpler or want to show a code based approach, please revise/delete my addition.

Beyond that, this is great! Let's talk more about the pivoting stuff today...I agree there's plenty in here without doing a pivot. I think a short separate lesson on pivots is probably best...could integrate with a spreadsheets lesson and use the CalEnviroscreen dataset. I can tackle that.

**Review by ryanpeek — CHANGES_REQUESTED** [review]
See my edits! So close...this is great, should be easy to wrap up.

**Comment by richpauloo** [comment]
Okay, in the name of efficiency, I squeezed some extra commits into this one. 

I added the major rivers to some plots, a CES score, the `m_` refactor across all scripts, and the dropdown menu on the main page. 

I'm going to start another branch and do another refactor, because I made a minimal example to figure out how to add the intro and int-adv course on the same page, at east locally (and it works great!!!). Need to figure out the deploy and then I'll do the refactor on this repo.

**Comment by ryanpeek** [comment]
Awesome! Sounds good. Look fwd to checking it out.

**Pull request merged**
